name: falcon_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1
  - altgraph=0.17.4
  - aom=3.9.1
  - blas=1.0
  - blosc=1.21.6
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-blosc2=2.15.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - cpuonly=2.0
  - dav1d=1.2.1
  - eigen=3.4.0
  - fftw=3.3.10
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmpy2=2.1.2
  - hdf5=1.14.3
  - icc_rt=2022.1.0
  - idna=3.7
  - imagecodecs=2024.6.1
  - imageio=2.33.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jxrlib=1.1
  - krb5=1.21.3
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libavif16=1.1.1
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcurl=8.10.1
  - libdeflate=1.21
  - libhwloc=2.11.1
  - libiconv=1.17
  - libitk=5.4.0
  - libjpeg-turbo=3.0.0
  - libpng=1.6.44
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.2.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - pefile=2024.8.26
  - pillow=10.4.0
  - pip=24.2
  - pthread-stubs=0.3
  - pthreads-win32=2.9.1
  - pybind11-abi=5
  - pydicom=2.3.1
  - pyinstaller=6.10.0
  - pyinstaller-hooks-contrib=2024.8
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.4.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=306
  - pywin32-ctypes=0.2.3
  - pyyaml=6.0.1
  - rav1e=0.6.6
  - requests=2.32.3
  - scikit-image=0.24.0
  - scipy=1.13.1
  - setuptools=75.1.0
  - simpleitk=2.4.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - svt-av1=2.2.1
  - sympy=1.13.2
  - tbb=2021.13.0
  - tifffile=2023.4.12
  - tk=8.6.13
  - torchvision=0.19.1
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib-ng=2.2.2
  - zstd=1.5.6
  - pip:
      - privatemodelarchitectures==0.1.1
      - pylibjpeg==2.0.1
      - pylibjpeg-libjpeg==2.2.0
      - pylibjpeg-openjpeg==2.3.0
      - python-gdcm==3.0.24.1
